version: "3.8"

services:
  web:
    image: elsachung/project-practice:latest
    ports:
      - "8080:8000"
    env_file:
      - .env # 容器啟動時，讀取 .env 並注入到容器內, 但.env 不會被打包進 Docker image
    restart: unless-stopped
